"""
Módulo de inferência em lote sobre tiles de teste.
"""

from .batch_predict import batch_predict
from .explainability_analysis import (
    build_promising_region_clusters,
    build_campaign_suggestion,
    build_sample_comparison_table,
    build_sample_heatmap_points,
    describe_region_opportunity,
    haversine_distance_km,
)
from .keras_binary_predict import collect_binary_predictions
from .transfer_geo_inference import (
    A11_RANKING_CACHE_FILENAME,
    DEFAULT_BAND_ORDER,
    DEFAULT_CLASS_NAMES,
    PredictionResult,
    RANKING_CACHE_FILENAME,
    TransferInferenceBundle,
    assess_chip_quality,
    build_dataset_probability_ranking,
    build_false_color_preview,
    build_rgb_preview,
    compute_gradcam_heatmap,
    clear_cache_dir,
    generate_dataset_sample_gradcam,
    load_a11_transfer_inference_bundle,
    load_transfer_inference_bundle,
    overlay_activation_heatmap,
    predict_chip_array,
    predict_point_from_earthdata,
    read_chip_tif,
    resolve_project_root,
    save_preview_png,
    search_earthdata_granules,
)

__all__ = [
    "batch_predict",
    "build_promising_region_clusters",
    "build_campaign_suggestion",
    "build_sample_comparison_table",
    "build_sample_heatmap_points",
    "describe_region_opportunity",
    "collect_binary_predictions",
    "haversine_distance_km",
    "A11_RANKING_CACHE_FILENAME",
    "DEFAULT_BAND_ORDER",
    "DEFAULT_CLASS_NAMES",
    "PredictionResult",
    "RANKING_CACHE_FILENAME",
    "TransferInferenceBundle",
    "assess_chip_quality",
    "build_dataset_probability_ranking",
    "build_false_color_preview",
    "build_rgb_preview",
    "compute_gradcam_heatmap",
    "clear_cache_dir",
    "generate_dataset_sample_gradcam",
    "load_a11_transfer_inference_bundle",
    "load_transfer_inference_bundle",
    "overlay_activation_heatmap",
    "predict_chip_array",
    "predict_point_from_earthdata",
    "read_chip_tif",
    "resolve_project_root",
    "save_preview_png",
    "search_earthdata_granules",
]
